// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByyp6wVbp1-cFUwt-f7xk9ik--1FRmO_w',
    appId: '1:692927470119:web:93d848f4da4fca83ff8c02',
    messagingSenderId: '692927470119',
    projectId: 'napito-8c168',
    authDomain: 'napito-8c168.firebaseapp.com',
    storageBucket: 'napito-8c168.firebasestorage.app',
    measurementId: 'G-GLQ685CYQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJEh7woXcVW6TMAVlfv0NsbD8sqlWXsg',
    appId: '1:692927470119:android:9cb9640754b49235ff8c02',
    messagingSenderId: '692927470119',
    projectId: 'napito-8c168',
    storageBucket: 'napito-8c168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkIDOTQyKUue0EXnFcMv27t1yZhBuf1M',
    appId: '1:692927470119:ios:63051e03efd65ed8ff8c02',
    messagingSenderId: '692927470119',
    projectId: 'napito-8c168',
    storageBucket: 'napito-8c168.firebasestorage.app',
    iosBundleId: 'com.example.msSalonTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKkIDOTQyKUue0EXnFcMv27t1yZhBuf1M',
    appId: '1:692927470119:ios:63051e03efd65ed8ff8c02',
    messagingSenderId: '692927470119',
    projectId: 'napito-8c168',
    storageBucket: 'napito-8c168.firebasestorage.app',
    iosBundleId: 'com.example.msSalonTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByyp6wVbp1-cFUwt-f7xk9ik--1FRmO_w',
    appId: '1:692927470119:web:1ac513119f108000ff8c02',
    messagingSenderId: '692927470119',
    projectId: 'napito-8c168',
    authDomain: 'napito-8c168.firebaseapp.com',
    storageBucket: 'napito-8c168.firebasestorage.app',
    measurementId: 'G-EKGD19Y8P4',
  );

}